---
title: "Health Metrics and the Spread of Infectious Diseases"
subtitle: "Machine Learning Applications and Spatial Modelling Analysis with R Book Club"
author: "The Data Science Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-health_metrics
description: "This website is the product of the Data Science Learning Community's Health Metrics and the Spread of Infectious Diseases Machine Learning Applications and Spatial Modelling Analysis with R Book Club."
---

# Welcome {.unnumbered}

Welcome to the Health Metrics and the Spread of Infectious Diseases Machine Learning Applications and Spatial Modelling Analysis with R book club!

This website is a companion for the book [*Health Metrics and the Spread of Infectious Diseases Machine Learning Applications and Spatial Modelling Analysis with R*](https://bookdown.org/fede_gazzelloni/hmsidR/) by Federica Gazzelloni (copyright 2025). This companion is available at [dslc.io/health_metrics](https://dslc.io/health_metrics).

This website is being developed by the [Data Science Learning Community](https://dslc.io). Follow along, and [join the community](https://dslc.io/join) to participate.

This companion follows the [Data Science Learning Community Code of Conduct](https://dslc.io/code_of_conduct.html).

## Book club meetings {.unnumbered}

-   Each week, a volunteer will present a chapter from the book (or part of a chapter).
    -   **This is the best way to learn the material!**
-   Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
-   More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-health_metrics).
-   Presentations will be recorded, and will be available on the [Data Science Learning Community YouTube Channel](https://dslc.io/youtube).

## Pace {.unnumbered}

-   We'll *try* to cover 1 chapter/week, but...
-   ...It's ok to split chapters when they feel like too much.
-   We will try to meet every week, but will likely take some breaks for holidays, etc.
